package com.opportunity.tree.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssumptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssumptionAllPropertiesEquals(Assumption expected, Assumption actual) {
        assertAssumptionAutoGeneratedPropertiesEquals(expected, actual);
        assertAssumptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssumptionAllUpdatablePropertiesEquals(Assumption expected, Assumption actual) {
        assertAssumptionUpdatableFieldsEquals(expected, actual);
        assertAssumptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssumptionAutoGeneratedPropertiesEquals(Assumption expected, Assumption actual) {
        assertThat(actual)
            .as("Verify Assumption auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssumptionUpdatableFieldsEquals(Assumption expected, Assumption actual) {
        assertThat(actual)
            .as("Verify Assumption relevant properties")
            .satisfies(a -> assertThat(a.getStatement()).as("check statement").isEqualTo(expected.getStatement()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getConfidence()).as("check confidence").isEqualTo(expected.getConfidence()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssumptionUpdatableRelationshipsEquals(Assumption expected, Assumption actual) {
        assertThat(actual)
            .as("Verify Assumption relationships")
            .satisfies(a -> assertThat(a.getSolution()).as("check solution").isEqualTo(expected.getSolution()));
    }
}
