package com.opportunity.tree.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssumptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssumptionAllPropertiesEquals(Assumption expected, Assumption actual) {
        assertAssumptionAutoGeneratedPropertiesEquals(expected, actual);
        assertAssumptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssumptionAllUpdatablePropertiesEquals(Assumption expected, Assumption actual) {
        assertAssumptionUpdatableFieldsEquals(expected, actual);
        assertAssumptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssumptionAutoGeneratedPropertiesEquals(Assumption expected, Assumption actual) {
        assertThat(actual)
            .as("Verify Assumption auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssumptionUpdatableFieldsEquals(Assumption expected, Assumption actual) {
        assertThat(actual)
            .as("Verify Assumption relevant properties")
            .satisfies(a -> assertThat(a.getStatement()).as("check statement").isEqualTo(expected.getStatement()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getImportance()).as("check importance").isEqualTo(expected.getImportance()))
            .satisfies(a -> assertThat(a.getEvidence()).as("check evidence").isEqualTo(expected.getEvidence()))
            .satisfies(a -> assertThat(a.getValidated()).as("check validated").isEqualTo(expected.getValidated()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssumptionUpdatableRelationshipsEquals(Assumption expected, Assumption actual) {
        assertThat(actual)
            .as("Verify Assumption relationships")
            .satisfies(a -> assertThat(a.getSolution()).as("check solution").isEqualTo(expected.getSolution()))
            .satisfies(a -> assertThat(a.getExperiments()).as("check experiments").isEqualTo(expected.getExperiments()));
    }
}
