package com.opportunity.tree.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EvidenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvidenceAllPropertiesEquals(Evidence expected, Evidence actual) {
        assertEvidenceAutoGeneratedPropertiesEquals(expected, actual);
        assertEvidenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvidenceAllUpdatablePropertiesEquals(Evidence expected, Evidence actual) {
        assertEvidenceUpdatableFieldsEquals(expected, actual);
        assertEvidenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvidenceAutoGeneratedPropertiesEquals(Evidence expected, Evidence actual) {
        assertThat(actual)
            .as("Verify Evidence auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvidenceUpdatableFieldsEquals(Evidence expected, Evidence actual) {
        assertThat(actual)
            .as("Verify Evidence relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvidenceUpdatableRelationshipsEquals(Evidence expected, Evidence actual) {
        assertThat(actual)
            .as("Verify Evidence relationships")
            .satisfies(a -> assertThat(a.getOpportunity()).as("check opportunity").isEqualTo(expected.getOpportunity()))
            .satisfies(a -> assertThat(a.getAssumption()).as("check assumption").isEqualTo(expected.getAssumption()));
    }
}
