package com.opportunity.tree.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExperimentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExperimentAllPropertiesEquals(Experiment expected, Experiment actual) {
        assertExperimentAutoGeneratedPropertiesEquals(expected, actual);
        assertExperimentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExperimentAllUpdatablePropertiesEquals(Experiment expected, Experiment actual) {
        assertExperimentUpdatableFieldsEquals(expected, actual);
        assertExperimentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExperimentAutoGeneratedPropertiesEquals(Experiment expected, Experiment actual) {
        assertThat(actual)
            .as("Verify Experiment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExperimentUpdatableFieldsEquals(Experiment expected, Experiment actual) {
        assertThat(actual)
            .as("Verify Experiment relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getHypothesis()).as("check hypothesis").isEqualTo(expected.getHypothesis()))
            .satisfies(a -> assertThat(a.getMethod()).as("check method").isEqualTo(expected.getMethod()))
            .satisfies(a -> assertThat(a.getSuccessCriteria()).as("check successCriteria").isEqualTo(expected.getSuccessCriteria()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getResult()).as("check result").isEqualTo(expected.getResult()))
            .satisfies(a -> assertThat(a.getLearnings()).as("check learnings").isEqualTo(expected.getLearnings()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExperimentUpdatableRelationshipsEquals(Experiment expected, Experiment actual) {
        assertThat(actual)
            .as("Verify Experiment relationships")
            .satisfies(a -> assertThat(a.getSolution()).as("check solution").isEqualTo(expected.getSolution()))
            .satisfies(a -> assertThat(a.getAssumptions()).as("check assumptions").isEqualTo(expected.getAssumptions()));
    }
}
