package com.opportunity.tree.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InterviewAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInterviewAllPropertiesEquals(Interview expected, Interview actual) {
        assertInterviewAutoGeneratedPropertiesEquals(expected, actual);
        assertInterviewAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInterviewAllUpdatablePropertiesEquals(Interview expected, Interview actual) {
        assertInterviewUpdatableFieldsEquals(expected, actual);
        assertInterviewUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInterviewAutoGeneratedPropertiesEquals(Interview expected, Interview actual) {
        assertThat(actual)
            .as("Verify Interview auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInterviewUpdatableFieldsEquals(Interview expected, Interview actual) {
        assertThat(actual)
            .as("Verify Interview relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getParticipant()).as("check participant").isEqualTo(expected.getParticipant()))
            .satisfies(a -> assertThat(a.getInterviewDate()).as("check interviewDate").isEqualTo(expected.getInterviewDate()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getRecordingUrl()).as("check recordingUrl").isEqualTo(expected.getRecordingUrl()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInterviewUpdatableRelationshipsEquals(Interview expected, Interview actual) {
        assertThat(actual)
            .as("Verify Interview relationships")
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()))
            .satisfies(a -> assertThat(a.getOpportunities()).as("check opportunities").isEqualTo(expected.getOpportunities()));
    }
}
