package com.opportunity.tree.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MeetingTranscriptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMeetingTranscriptAllPropertiesEquals(MeetingTranscript expected, MeetingTranscript actual) {
        assertMeetingTranscriptAutoGeneratedPropertiesEquals(expected, actual);
        assertMeetingTranscriptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMeetingTranscriptAllUpdatablePropertiesEquals(MeetingTranscript expected, MeetingTranscript actual) {
        assertMeetingTranscriptUpdatableFieldsEquals(expected, actual);
        assertMeetingTranscriptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMeetingTranscriptAutoGeneratedPropertiesEquals(MeetingTranscript expected, MeetingTranscript actual) {
        assertThat(actual)
            .as("Verify MeetingTranscript auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMeetingTranscriptUpdatableFieldsEquals(MeetingTranscript expected, MeetingTranscript actual) {
        assertThat(actual)
            .as("Verify MeetingTranscript relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getMeetingDate()).as("check meetingDate").isEqualTo(expected.getMeetingDate()))
            .satisfies(a -> assertThat(a.getAttendees()).as("check attendees").isEqualTo(expected.getAttendees()))
            .satisfies(a -> assertThat(a.getBody()).as("check body").isEqualTo(expected.getBody()))
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getEditedDate()).as("check editedDate").isEqualTo(expected.getEditedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMeetingTranscriptUpdatableRelationshipsEquals(MeetingTranscript expected, MeetingTranscript actual) {
        assertThat(actual)
            .as("Verify MeetingTranscript relationships")
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()))
            .satisfies(a -> assertThat(a.getOutcome()).as("check outcome").isEqualTo(expected.getOutcome()))
            .satisfies(a -> assertThat(a.getOpportunity()).as("check opportunity").isEqualTo(expected.getOpportunity()))
            .satisfies(a -> assertThat(a.getSolution()).as("check solution").isEqualTo(expected.getSolution()))
            .satisfies(a -> assertThat(a.getAssumption()).as("check assumption").isEqualTo(expected.getAssumption()))
            .satisfies(a -> assertThat(a.getEvidence()).as("check evidence").isEqualTo(expected.getEvidence()));
    }
}
