package com.opportunity.tree.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NodeHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeHistoryAllPropertiesEquals(NodeHistory expected, NodeHistory actual) {
        assertNodeHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertNodeHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeHistoryAllUpdatablePropertiesEquals(NodeHistory expected, NodeHistory actual) {
        assertNodeHistoryUpdatableFieldsEquals(expected, actual);
        assertNodeHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeHistoryAutoGeneratedPropertiesEquals(NodeHistory expected, NodeHistory actual) {
        assertThat(actual)
            .as("Verify NodeHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeHistoryUpdatableFieldsEquals(NodeHistory expected, NodeHistory actual) {
        assertThat(actual)
            .as("Verify NodeHistory relevant properties")
            .satisfies(a -> assertThat(a.getNodeType()).as("check nodeType").isEqualTo(expected.getNodeType()))
            .satisfies(a -> assertThat(a.getNodeId()).as("check nodeId").isEqualTo(expected.getNodeId()))
            .satisfies(a -> assertThat(a.getEventType()).as("check eventType").isEqualTo(expected.getEventType()))
            .satisfies(a -> assertThat(a.getSummary()).as("check summary").isEqualTo(expected.getSummary()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeHistoryUpdatableRelationshipsEquals(NodeHistory expected, NodeHistory actual) {
        // empty method
    }
}
