package com.opportunity.tree.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NodeLinkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeLinkAllPropertiesEquals(NodeLink expected, NodeLink actual) {
        assertNodeLinkAutoGeneratedPropertiesEquals(expected, actual);
        assertNodeLinkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeLinkAllUpdatablePropertiesEquals(NodeLink expected, NodeLink actual) {
        assertNodeLinkUpdatableFieldsEquals(expected, actual);
        assertNodeLinkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeLinkAutoGeneratedPropertiesEquals(NodeLink expected, NodeLink actual) {
        assertThat(actual)
            .as("Verify NodeLink auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeLinkUpdatableFieldsEquals(NodeLink expected, NodeLink actual) {
        assertThat(actual)
            .as("Verify NodeLink relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeLinkUpdatableRelationshipsEquals(NodeLink expected, NodeLink actual) {
        assertThat(actual)
            .as("Verify NodeLink relationships")
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()))
            .satisfies(a -> assertThat(a.getOutcome()).as("check outcome").isEqualTo(expected.getOutcome()))
            .satisfies(a -> assertThat(a.getOpportunity()).as("check opportunity").isEqualTo(expected.getOpportunity()))
            .satisfies(a -> assertThat(a.getSolution()).as("check solution").isEqualTo(expected.getSolution()))
            .satisfies(a -> assertThat(a.getAssumption()).as("check assumption").isEqualTo(expected.getAssumption()))
            .satisfies(a -> assertThat(a.getEvidence()).as("check evidence").isEqualTo(expected.getEvidence()));
    }
}
