package com.opportunity.tree.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OpenQuestionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpenQuestionAllPropertiesEquals(OpenQuestion expected, OpenQuestion actual) {
        assertOpenQuestionAutoGeneratedPropertiesEquals(expected, actual);
        assertOpenQuestionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpenQuestionAllUpdatablePropertiesEquals(OpenQuestion expected, OpenQuestion actual) {
        assertOpenQuestionUpdatableFieldsEquals(expected, actual);
        assertOpenQuestionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpenQuestionAutoGeneratedPropertiesEquals(OpenQuestion expected, OpenQuestion actual) {
        assertThat(actual)
            .as("Verify OpenQuestion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpenQuestionUpdatableFieldsEquals(OpenQuestion expected, OpenQuestion actual) {
        assertThat(actual)
            .as("Verify OpenQuestion relevant properties")
            .satisfies(a -> assertThat(a.getQuestionText()).as("check questionText").isEqualTo(expected.getQuestionText()))
            .satisfies(a -> assertThat(a.getDone()).as("check done").isEqualTo(expected.getDone()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpenQuestionUpdatableRelationshipsEquals(OpenQuestion expected, OpenQuestion actual) {
        assertThat(actual)
            .as("Verify OpenQuestion relationships")
            .satisfies(a -> assertThat(a.getOpportunity()).as("check opportunity").isEqualTo(expected.getOpportunity()));
    }
}
