package com.opportunity.tree.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OpportunityLinkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportunityLinkAllPropertiesEquals(OpportunityLink expected, OpportunityLink actual) {
        assertOpportunityLinkAutoGeneratedPropertiesEquals(expected, actual);
        assertOpportunityLinkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportunityLinkAllUpdatablePropertiesEquals(OpportunityLink expected, OpportunityLink actual) {
        assertOpportunityLinkUpdatableFieldsEquals(expected, actual);
        assertOpportunityLinkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportunityLinkAutoGeneratedPropertiesEquals(OpportunityLink expected, OpportunityLink actual) {
        assertThat(actual)
            .as("Verify OpportunityLink auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportunityLinkUpdatableFieldsEquals(OpportunityLink expected, OpportunityLink actual) {
        assertThat(actual)
            .as("Verify OpportunityLink relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportunityLinkUpdatableRelationshipsEquals(OpportunityLink expected, OpportunityLink actual) {
        assertThat(actual)
            .as("Verify OpportunityLink relationships")
            .satisfies(a -> assertThat(a.getOpportunity()).as("check opportunity").isEqualTo(expected.getOpportunity()));
    }
}
