package com.opportunity.tree.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OpportunityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportunityAllPropertiesEquals(Opportunity expected, Opportunity actual) {
        assertOpportunityAutoGeneratedPropertiesEquals(expected, actual);
        assertOpportunityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportunityAllUpdatablePropertiesEquals(Opportunity expected, Opportunity actual) {
        assertOpportunityUpdatableFieldsEquals(expected, actual);
        assertOpportunityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportunityAutoGeneratedPropertiesEquals(Opportunity expected, Opportunity actual) {
        assertThat(actual)
            .as("Verify Opportunity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportunityUpdatableFieldsEquals(Opportunity expected, Opportunity actual) {
        assertThat(actual)
            .as("Verify Opportunity relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getValuerating()).as("check valuerating").isEqualTo(expected.getValuerating()))
            .satisfies(a -> assertThat(a.getPriority()).as("check priority").isEqualTo(expected.getPriority()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportunityUpdatableRelationshipsEquals(Opportunity expected, Opportunity actual) {
        assertThat(actual)
            .as("Verify Opportunity relationships")
            .satisfies(a -> assertThat(a.getOutcome()).as("check outcome").isEqualTo(expected.getOutcome()))
            .satisfies(a -> assertThat(a.getParent()).as("check parent").isEqualTo(expected.getParent()))
            .satisfies(a -> assertThat(a.getInterviews()).as("check interviews").isEqualTo(expected.getInterviews()))
            .satisfies(a -> assertThat(a.getTags()).as("check tags").isEqualTo(expected.getTags()));
    }
}
