package com.opportunity.tree.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OutcomeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOutcomeAllPropertiesEquals(Outcome expected, Outcome actual) {
        assertOutcomeAutoGeneratedPropertiesEquals(expected, actual);
        assertOutcomeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOutcomeAllUpdatablePropertiesEquals(Outcome expected, Outcome actual) {
        assertOutcomeUpdatableFieldsEquals(expected, actual);
        assertOutcomeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOutcomeAutoGeneratedPropertiesEquals(Outcome expected, Outcome actual) {
        assertThat(actual)
            .as("Verify Outcome auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOutcomeUpdatableFieldsEquals(Outcome expected, Outcome actual) {
        assertThat(actual)
            .as("Verify Outcome relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getMetric()).as("check metric").isEqualTo(expected.getMetric()))
            .satisfies(a -> assertThat(a.getTargetValue()).as("check targetValue").isEqualTo(expected.getTargetValue()))
            .satisfies(a -> assertThat(a.getCurrentValue()).as("check currentValue").isEqualTo(expected.getCurrentValue()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getTargetDate()).as("check targetDate").isEqualTo(expected.getTargetDate()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOutcomeUpdatableRelationshipsEquals(Outcome expected, Outcome actual) {
        assertThat(actual)
            .as("Verify Outcome relationships")
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
