package com.opportunity.tree.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SolutionLinkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolutionLinkAllPropertiesEquals(SolutionLink expected, SolutionLink actual) {
        assertSolutionLinkAutoGeneratedPropertiesEquals(expected, actual);
        assertSolutionLinkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolutionLinkAllUpdatablePropertiesEquals(SolutionLink expected, SolutionLink actual) {
        assertSolutionLinkUpdatableFieldsEquals(expected, actual);
        assertSolutionLinkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolutionLinkAutoGeneratedPropertiesEquals(SolutionLink expected, SolutionLink actual) {
        assertThat(actual)
            .as("Verify SolutionLink auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolutionLinkUpdatableFieldsEquals(SolutionLink expected, SolutionLink actual) {
        assertThat(actual)
            .as("Verify SolutionLink relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolutionLinkUpdatableRelationshipsEquals(SolutionLink expected, SolutionLink actual) {
        assertThat(actual)
            .as("Verify SolutionLink relationships")
            .satisfies(a -> assertThat(a.getSolution()).as("check solution").isEqualTo(expected.getSolution()));
    }
}
