package com.opportunity.tree.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TeamMemberAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamMemberAllPropertiesEquals(TeamMember expected, TeamMember actual) {
        assertTeamMemberAutoGeneratedPropertiesEquals(expected, actual);
        assertTeamMemberAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamMemberAllUpdatablePropertiesEquals(TeamMember expected, TeamMember actual) {
        assertTeamMemberUpdatableFieldsEquals(expected, actual);
        assertTeamMemberUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamMemberAutoGeneratedPropertiesEquals(TeamMember expected, TeamMember actual) {
        assertThat(actual)
            .as("Verify TeamMember auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamMemberUpdatableFieldsEquals(TeamMember expected, TeamMember actual) {
        assertThat(actual)
            .as("Verify TeamMember relevant properties")
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()))
            .satisfies(a -> assertThat(a.getJoinedDate()).as("check joinedDate").isEqualTo(expected.getJoinedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamMemberUpdatableRelationshipsEquals(TeamMember expected, TeamMember actual) {
        assertThat(actual)
            .as("Verify TeamMember relationships")
            .satisfies(a -> assertThat(a.getTeam()).as("check team").isEqualTo(expected.getTeam()));
    }
}
