export enum HistoryEventType {
  CREATED = 'CREATED',

  STATUS_CHANGED = 'STATUS_CHANGED',

  CONFIDENCE_CHANGED = 'CONFIDENCE_CHANGED',

  PRIORITY_CHANGED = 'PRIORITY_CHANGED',

  VALUE_CHANGED = 'VALUE_CHANGED',

  MOVED = 'MOVED',

  COMMENT_ADDED = 'COMMENT_ADDED',

  COMMENT_DELETED = 'COMMENT_DELETED',

  LINK_ADDED = 'LINK_ADDED',

  LINK_REMOVED = 'LINK_REMOVED',

  QUESTION_ADDED = 'QUESTION_ADDED',
}
