export enum OpportunityStatus {
  IDENTIFIED = 'IDENTIFIED',

  EXPLORING = 'EXPLORING',

  PRIORITISED = 'PRIORITISED',

  IN_PROGRESS = 'IN_PROGRESS',

  ADDRESSED = 'ADDRESSED',

  PARKED = 'PARKED',

  DISCARDED = 'DISCARDED',
}
