export enum SolutionStatus {
  IDEA = 'IDEA',

  ASSUMPTION_MAPPING = 'ASSUMPTION_MAPPING',

  TESTING = 'TESTING',

  VALIDATED = 'VALIDATED',

  INVALIDATED = 'INVALIDATED',

  SHIPPED = 'SHIPPED',

  DROPPED = 'DROPPED',
}
